---
name: push-tag
on:
  push:
    tags:
      - '*'
jobs:
  build-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            codebrewco/nginx-proxy-fpm:latest
            codebrewco/nginx-proxy-fpm:${{ github.ref_name }}
